### ISSUE TITLE
Import of language tags with more than 2 letters (e.g. @en-US) not possible

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/OntoWiki#111]
When I create a knew knowledge base via "Paste Source", I get the following error message:

    Error importing knowledge base: Graph <http://test.com> could not be imported: Character "U" not allowed in language tags.

AFAIK this relates to the line `og:site_name "Best Buy"@en-US ;` which uses an extended language tag.

The full source code of the problem-causing RDF extracted from [a best buy TV offer](http://www.bestbuy.com/site/Samsung+-+50%26%2334%3B+Class+-+LED+-+1080p+-+120Hz+-+Smart+-+3D+-+HDTV/4922152.p?skuId=4922152&id=1218581208736):

    @prefix fb: <http://www.facebook.com/2008/fbml> .
    @prefix og: <http://ogp.me/ns#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix xhv: <http://www.w3.org/1999/xhtml/vocab#> .
    @prefix xml: <http://www.w3.org/XML/1998/namespace> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

    <http://www.bestbuy.com/site/Samsung+-+50%26%2334%3B+Class+-+LED+-+1080p+-+120Hz+-+Smart+-+3D+-+HDTV/4922152.p?skuId=4922152&id=1218581208736> og:description "Best Buy ExclusiveENERGY STAR QualifiedLearn more about smart products."@en-US ;
         og:image "http://images.bestbuy.com:80/BestBuy_US/images/products/4922/4922152_sb.jpg"@en-US ;
         og:site_name "Best Buy"@en-US ;
         og:title "Samsung - 50\" Class - LED - 1080p - 120Hz - Smart - 3D - HDTV"@en-US ;
         og:type "product"@en-US ;
         og:upc "036725238220"@en-US ;
         og:url "http://www.bestbuy.com:80/site/Samsung---50%26%2334%3B-Class---LED---1080p---120Hz---Smart---3D---HDTV/4922152.p?id=1218581208736&skuId=4922152"@en-US ;
         <http://www.facebook.com/2008/fbmlapp_id> "125188000891129"@en-US ;
         xhv:stylesheet
             <http://images.bestbuy.com:80/BestBuy_US/js/busops-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/buttons-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/commerce-capability-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/fitguide.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/global-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/google-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/main_icon_sprite-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/pdp-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/snippets-min.css>,
             <http://images.bestbuy.com:80/BestBuy_US/store/styles/tabs-min.css> .

**Comment by pfrischmuth** [comment]
This was a parser issue in Erfurt. It is fixed with commit 40c1caa in Erfurt.
