### ISSUE TITLE
Import data with RDFa - "the data is not available." or endless waiting dialog

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/OntoWiki#112]
The following Good Relations RDFa example pages either show "the data is not available." or endlessly (I waited several minutes) show a waiting dialog  after I enter the URL in the location bar and click on "Import data with RDFa". In fact I did not find a working example yet.

The examples are from `http://notes.3kbo.com/goodrelations-sites` and I tried:

http://www.kmart.com/automotive-emergency-travel-general-items-travel-mugs/s-1206808763
http://www.sears.com/shc/s/p_10153_12605_07180844000P
http://shop.oreilly.com/product/9780596007683.do
http://www.universum-shop.de/go/DP4Q2HE68YA7JM53XD3OOGVUYTJ5OW31?action=ProdDetailsproduct_uuid=SWBV7SQBGJMT68TOS9Z3CMWQJOKDS4UU
http://www.waffen-frank-shop.de/index.php?sid=d396db5bc51906ea5b57ec01e16197bd&&redirected=1

**Comment by shinobu** [comment]
this has been fixed with https://github.com/AKSW/Erfurt/pull/110
