### ISSUE TITLE
make cs-check and other does not work in submodule mode

### ISSUE THREAD

**Issue by seebi** [AKSW/OntoWiki#176]
I've done

    make cs-install-submodule MPATH=extensions/article/
    cd extensions/article
    make cs-check

and I got

    /Users/seebi/Projects/OntoWiki.git/extensions/article/../../application/tests/CodeSniffer/cs-scripts.sh -c "-s --report=summary    /Users/seebi/.config/zsh/functions.d:/usr/local/share/zsh-completions:/usr/share/zsh/site-functions:/usr/share/zsh/4.3.11/functions"
    ERROR: The file "/Users/seebi/.config/zsh/functions.d:/usr/local/share/zsh-completions:/usr/share/zsh/site-functions:/usr/share/zsh/4.3.11/functions" does not exist.

**Comment by shinobu** [comment]
code sniffer got changed with composer now -- closed
