### ISSUE TITLE
Linked Data Wrapper is not able to parse resources containing HashUris in turtle represenation

### ISSUE THREAD

**Issue by MichaelMartin** [AKSW/OntoWiki#199]
I tried to receive data about:

http://purl.org/linked-data/cube#Observation

this URL redirects to :

http://publishing-statistical-data.googlecode.com/svn/trunk/specs/src/main/vocab/cube.ttl#Observation

which is a turtle file containing the whole ontology.

OntoWiki answers with:

An error occured: Parsing failed: Not well-formed (invalid token)

**Comment by pfrischmuth** [comment]
This issue was due to a parser bug in Erfurt and is meanwhile already fixed (refer to #111 in the Erfurt repository). I added the above turtle file as a valid test resource to the Erfurt library and verified that the test failed before the fix and succeeded after the fix.
