### ISSUE TITLE
No tuples available at this result index Error

### ISSUE THREAD

**Issue by smouzakitis** [AKSW/OntoWiki#209]
Hello, i have setup ontowiki according to the instructions using virtuoso as a backend. The odbctest.php worked great.

However when i run ontowiki i get:

No tuples available at this result index Error in C:\xampp\htdocs\ontowiki\libraries\Erfurt\Erfurt\Store\Adapter\Virtuoso.php on line 160

for anonymous users.

When i login as the admin the error disappears.

Also the Create Knowledge database from either file / web / paste source doesn't seem to work at all: 

Error importing knowledge base: Graph <http://aksw.org/> could not be imported: Error importing statements: SQL Error: [OpenLink][Virtuoso ODBC Driver][Virtuoso Server]FA112: Can't stat file 'C: mpp mpphpE.tmp', error (2) : No such file or directory () in query: CALL DB.DBA.RDF_LOAD_RDFXML(FILE_TO_STRING_OUTPUT('C:\xampp\tmp\phpE.tmp'), 'http://aksw.org/', 'http://aksw.org/')

**Comment by shinobu** [comment]
The Error `No tuples available at this result index Error in C:\xampp\htdocs\ontowiki\libraries\Erfurt\Erfurt\Store\Adapter\Virtuoso.php on line 160`
is reproducable for the old .zip archive you can get at /downloads.
But this error does no longer appear in the actual OntoWiki Version (though i needed prepare the folder for the test in ubuntu).
Importing Data does work for the actual version as well.

**Comment by white-gecko** [comment]
Do you mean 0.9.11 with “old” .zip?

**Comment by white-gecko** [comment]
respective, which Erfurt version?

**Comment by white-gecko** [comment]
This issue occurred on v0.9.6-21 but doesn't occur on the current develop branch. So we consider it as fixed. Please try one of the later releases.
