### ISSUE TITLE
$this->_properties not set in DatagatheringPlugin

### ISSUE THREAD

**Issue by kkda** [AKSW/OntoWiki#235]
Notice: Trying to get property of non-object in https://github.com/AKSW/OntoWiki/blob/93acc3db31d016972575863c8ffd4798ac258757/extensions/datagathering/DatagatheringPlugin.php#L340

$this->_properties has its default value there.

It looks like it was removed in https://github.com/AKSW/OntoWiki/commit/67e5db69178f6430a460ff8de12c9112ce5b60cc#diff-3. The old code doesn't work as is.

**Comment by pfrischmuth** [comment]
This was already fixed in the meantime, since the mentioned line of code now accesses the `_privateConfig` property instead of the `_properties` property (which was clearly wrong).

**Comment by white-gecko** [comment]
@pfrischmuth are you able to find the respective commit, where this was fixed? Just for the references.

**Comment by pfrischmuth** [comment]
8b9d403767ea8c44e4f78d708a86ac1c0376690d
