### ISSUE TITLE
The "autocomplete" seems to freeze when a nonexistent resource name is entered

### ISSUE THREAD

**Issue by marek-dudas** [AKSW/OntoWiki#275]
If a name of a resource that does not exist in the current knowledge base is entered into a property field in the Create New Instance dialog (e.g. medicine.drug_formulation.active_ingredients field in Screenshot 1) the “autocomplete” function keeps searching (or at least the “searching” icon is displayed) but no result is returned. When the input is then changed to a name of an existing resource, the “searching” icon is still displayed and no results are returned. Closing and reopening the Create New Instance dialog solves this - if an existing resource name is entered then, “autocomplete” returns result correctly. 

Happens on the following configuration:
Configuration 1:
Ubuntu 12.04.4
Virtuoso Opensource 07.00.3203 
PHP 5.4.22-1+debphp.org~precise+1
Erfurt & RDFauthor: latest git versions as of 11-20-2013
Ontowiki 0.9.11 git (as of 11-20-2013)

With a different configuration (2), entering a nonexistent resource name correctly returns “auto-generated URI” for a new resource. However, in configuration 2 “autocomplete” appears to be more unstable then in configuration 1. In some cases (unable to simulate exact circumstances), the search freezes as described above even if a name of an existing entity is entered.
Reopening the dialog does not help then. Clearing caches using the Debug menu seems to help. 
We were unable to find exact circumstances when this happens. It might be just something wrong with configuration 2.

Configuration 2
CentOS release 5.6
Virtuoso Opensource 06.01.3127
PHP 5.4.22
Erfurt & RDFauthor: latest git versions as of 11-20-2013
Ontowiki 0.9.11 git (as of 11-20-2013)

**Comment by white-gecko** [comment]
Moved to https://github.com/AKSW/RDFauthor/issues/49
