### ISSUE TITLE
Edit Properties dialog shows only 5 of 7 values of a property

### ISSUE THREAD

**Issue by marek-dudas** [AKSW/OntoWiki#277]
It seems that the Edit Properties dialog is limited to show only 5 values of one property even though there are more. I thought maybe the "is large" option of the knowledge base configuration is supposed to solve this but checking it makes no difference.
Example: see the first screenshot - there are 7 triples of "AllianceHealthcare gr:offers ***", but only 5 of them is displayed in the Edit Properties dialog in the second screenshot. (Also, for some reason the gr:offers property is displayed twice there as "gr:offers" and "offers (0..*)" even though it is the same property, but I can live with that.)

![alliance_offers_list](https://f.cloud.github.com/assets/6452538/2123832/3d9db0be-9234-11e3-92e2-cf184dd5eaaf.png)
![alliance_offers_edit](https://f.cloud.github.com/assets/6452538/2123836/4791995a-9234-11e3-9535-ddc3735d2bdf.png)

**Comment by white-gecko** [comment]
@splattater @nucknorris did you encounter this issue in the amsl branch an maybe have a solution for it?

**Comment by nucknorris** [comment]
We don't have any other solution for the inline editor thus far but you can bypass the problem by using the popover window to edit the resource. (Resouce -> Edit Resource)

**Comment by white-gecko** [comment]
Moved to https://github.com/AKSW/RDFauthor/issues/48
