### ISSUE TITLE
On (Re)generate Site Page Cache

### ISSUE THREAD

**Issue by mgns** [AKSW/OntoWiki#297]
receive fatal error when clicking (Re)generate:
Class 'GearmanClient' not found in /var/www/ontowiki/libraries/Erfurt/library/Erfurt/Worker/Frontend.php on line 55

on page http://domain/ontowiki/site/regenerateCache

Gearman Extension is not installed

**Comment by white-gecko** [comment]
Moved to site extension: https://github.com/AKSW/site.ontowiki/issues/54
