### ISSUE TITLE
Erfurt error while using csvimport extention

### ISSUE THREAD

**Issue by iseliva** [AKSW/OntoWiki#299]
The following error appears after installation the csvimport extension when trying  to  import CSV data:

    No valid user was given.
    Erfurt_Ac_Exception
    
    /var/www/OntoWiki/libraries/Erfurt/library/Erfurt/Ac/Default.php@570 
    #0: Erfurt_Ac_Default->_getUser@/var/www/OntoWiki/libraries/Erfurt/library/Erfurt/Ac/Default.php:335
    #1: Erfurt_Ac_Default->areModelsAllowed@/var/www/OntoWiki/libraries/Erfurt/library/Erfurt/Store.php:2271
    #2: Erfurt_Store->_checkAcBatch@/var/www/OntoWiki/libraries/Erfurt/library/Erfurt/Store.php:878
    #3: Erfurt_Store->getAvailableModels@/var/www/OntoWiki/extensions/modellist/ModellistModule.php:31
    #4: ModellistModule->init@/var/www/OntoWiki/application/classes/OntoWiki/Module.php:151
    #5: OntoWiki_Module->__construct@/var/www/OntoWiki/application/classes/OntoWiki/Module/Registry.php:284
    #6: OntoWiki_Module_Registry->getModule@/var/www/OntoWiki/application/classes/OntoWiki/View.php:206
    #7: OntoWiki_View->module@/var/www/OntoWiki/application/classes/OntoWiki/View.php:152
    #8: OntoWiki_View->modules@/var/www/OntoWiki/application/classes/OntoWiki/Controller/Base.php:195
    #9: OntoWiki_Controller_Base->preDispatch@/var/www/OntoWiki/libraries/Zend/Controller/Action.php:502
    #10: Zend_Controller_Action->dispatch@/var/www/OntoWiki/libraries/Zend/Controller/Dispatcher/Standard.php:295
    #11: Zend_Controller_Dispatcher_Standard->dispatch@/var/www/OntoWiki/libraries/Zend/Controller/Front.php:954
    #12: Zend_Controller_Front->dispatch@/var/www/OntoWiki/libraries/Zend/Application/Bootstrap/Bootstrap.php:97
    #13: Zend_Application_Bootstrap_Bootstrap->run@/var/www/OntoWiki/libraries/Zend/Application.php:366
    #14: Zend_Application->run@/var/www/OntoWiki/index.php:188

Ubuntu Server 12.04

**Comment by shinobu** [comment]
moved to https://github.com/AKSW/csvimport.ontowiki/issues/29 as this is the appropriate place for the issue
closed
