### ISSUE TITLE
Deleting triples with large literals

### ISSUE THREAD

**Issue by white-gecko** [AKSW/OntoWiki#303]
Deleting triples with large literals sometimes doesn't work. This results in the effect, that editing a large literal will infect create a new large literal, while the old literal remains.

**Comment by shinobu** [comment]
a working test to prove this error was added into StoreIntegrationTest.php in commit 99fd452

**Comment by pfrischmuth** [comment]
This is an Erfurt issue and thus fixed in the Erfurt repo... Refer to AKSW/Erfurt#108

**Comment by pfrischmuth** [comment]
Issues was fixed in an Erfurt feature branch... Will be merged soon (before the 1.0 release)... Refer to AKSW/Erfurt#109 pull request

**Comment by white-gecko** [comment]
Did you manage to reproduce the issue on current Erfurt develop? I couldn't anymore.
