### ISSUE TITLE
Image Picker empty

### ISSUE THREAD

**Issue by amrapalijz** [AKSW/OntoWiki#305]
When I add the property "depiction" or "screenshot" while editing any resource, the ImagePicker appears empty. See attached screenshot.
![screen shot 2014-05-30 at 11 17 57](https://cloud.githubusercontent.com/assets/713103/3129956/4eb5f3ba-e7ee-11e3-94fe-524ba86651d5.png)

**Comment by white-gecko** [comment]
The picasa URL doesn't seem to be valid anymore

**Comment by shinobu** [comment]
this feature will be deleted in 1.0

**Comment by white-gecko** [comment]
In which commit did you remove the image picker? Could you please provide the commit hash/id in this issue?

**Comment by shinobu** [comment]
Removed in https://github.com/AKSW/RDFauthor/commit/6e8193443d3d519db10d00a6d6d6d63690fdc051
