### ISSUE TITLE
Finding Sparql End point in Ontowiki

### ISSUE THREAD

**Issue by spawankumar** [AKSW/OntoWiki#312]
Hello,
I currently looking to find SPARQL end point(Hyperlink) in ontowiki super admin area. Can you please let me know were can I look for it. Man thanks

**Comment by white-gecko** [comment]
The OntoWiki SPARQL endpoint is located at: `http://<ontowiki base URI>/queries/editor`. But you have to select a model before, e.g. by using the `?m=<urlencoded model URI>` argument.
