### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by dgrolin** [AKSW/OntoWiki#314]
I am very interested in trying on OntoWiki, which would fit a project that I am looking to do. Unfortunately, I have not been able to install it. Apache does not provide windows installers and so I have had to go fish for something else. I am using XAMPP. I have followed the instructions as well as I could with several of the intermittent tests working (e.g. test.php and odbctest). However, when I try the final strep that is supposed to give me OntoWiki I get the following message:

Fatal error: Class 'Zend\Log\Writer\AbstractWriter' not found in C:\xampp\htdocs\ontowiki-0.9.6-21\libraries\Zend\Log\Writer\Null.php on line 13

If I place an explicit include statement in Null.php to get the file AbstractWriter it gets another error in another file. So for some reason or another the PHP files are not finding each other.

![localhostontowiki-0 9](https://cloud.githubusercontent.com/assets/10184617/5427331/c1c4fbb4-83a0-11e4-9423-51188eb7d470.jpg)

Any suggestions on why this is happening?

Regards, Daniel

**Comment by white-gecko** [comment]
Dear Daniel,
sorry for letting you wait. This looks like an issue with your zend installation. Did you place the latest zend 1.x version (e.g. 1.12.9) in `<owroot>/libraries/Zend` ? Or did you install zend2?

**Comment by white-gecko** [comment]
I assume this issue can be closed. Please reopen it, if you are facing further trouble.

**Comment by white-gecko** [comment]
Installation of the correct dependencies will also be improved using composer. See #320.

**Comment by dgrolin** [comment]
Dear Natanael,

I think that I followed the instructions as well as was possible. It was in
the directory indicated and it was zend not zend2. As noted I will not be
able to invest anymore time it getting this up and running. I suspect that
I am not the only one for whom this is a breaking point. For me to
reconsider and have a second go at OntoWiki there will have to be an
installer. Is that likely to ever happen?

Regards,

Daniel
