### ISSUE TITLE
Virtuoso 7.10.3211 crashes during OntoWiki first-run attempt

### ISSUE THREAD

**Issue by marek-dudas** [AKSW/OntoWiki#315]
I tried installing OntoWiki by git-cloning the latest version on Ubuntu 14.04 with Virtuoso opensource 7.10.3211. Every time I try to run OntoWiki, Virtuoso just stops and OntoWiki says it "lost connection". I was unable to find any errors in Virtuoso log. Should OntoWiki work with Virtuoso 7, or is it tested only with version 6? I will be happy to try to provide any more details if needed.

**Comment by white-gecko** [comment]
Am 14.04.2015 um 18:39 schrieb Marek Dudas:
>
> I tried installing OntoWiki by git-cloning the latest version on 
> Ubuntu 14.04 with Virtuoso opensource 7.10.3211. Every time I try to 
> run OntoWiki, Virtuoso just stops and OntoWiki says it "lost 
> connection". I was unable to find any errors in Virtuoso log. Should 
> OntoWiki work with Virtuoso 7, or is it tested only with version 6? I 
> will be happy to try to provide any more details if needed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AKSW/OntoWiki/issues/315>.
>
Hello Marek,
I'm running OntoWiki on Virtuoso 7 in one setup but I've heard of some 
issues with OntoWiki+Virtuoso 7 from other colleges. OntoWiki mostly 
used and tested on Virtuoso 6 but I think it is a good idea to further 
test it on Virtuoso 7.

Natanael

**Comment by white-gecko** [comment]
I'm running OntoWiki on Virtuoso 07.10.3211 and it works quite well. Please reopen this issue if the problem is still existent.
