### ISSUE TITLE
Zend_Controller_Response_Exception: Cannot send headers; headers already sent 

### ISSUE THREAD

**Issue by cckweiss** [AKSW/OntoWiki#316]
I am trying to install OntoWiki on an Amazon Linux (essentially CentOS) system, using the Virtuoso backend. I followed this procedure to install the components:

http://pastebin.com/7EmayPDT

That installs the following:

1) Virtuoso 6.1.8
2) Apache httpd 2.2.29
3) PHP 5.6.7
4) Ontowiki 0.9.6-21

I confirmed that Virtuoso, httpd, and PHP are all working properly. I can use ODBC to connect to the Virtuoso backend and retrieve a list of the installed graphs:

http://www.openlinksw.com/schemas/virtrdf#
http://localhost:8890/sparql
http://localhost:8890/DAV/
http://www.w3.org/2002/07/owl#
http://localhost/OntoWiki/Config/
http://ns.ontowiki.net/SysOnt/

However, when I attempt to go to the OntoWiki application (http://udfr-tmp.cdlib.org/ontowiki), I get the following error:

Warning: odbc_result(): No tuples available at this result index in /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Erfurt/Erfurt/Store/Adapter/Virtuoso.php on line 160

The debug output provides this additional information:

Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Erfurt/Erfurt/Store/Adapter/Virtuoso.php, line 160
/apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Controller/Response/Abstract.php@323

That is followed by a lengthy stacktrace, appended at the end of this message.

I researched the 'headers already sent' error, and found this:

http://stackoverflow.com/questions/6420733/how-to-fix-cannot-send-headers-headers-already-sent-in-zend

That posting appears to describe my problem exactly. I looked at the files itemized in the stack trace, and every one of them is missing the closing '?>' PHP tag. I tried adding those tags. The very first file referenced, ontowiki/libraries/Erfurt/Erfurt/Store/Adapter/Virtuoso.php, disappeared from the stacktrace when I added the closing tag. However, I went ahead and added the closing tag to all the other files, and nothing changed. I am still getting the exact same error and stacktrace, just without the reference to Virtuoso.php.

Can you identify where I went wrong?

--Ken Weiss

full error message and stacktrace follows:

Warning: odbc_result(): No tuples available at this result index in /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Erfurt/Erfurt/Store/Adapter/Virtuoso.php on line 160
OntoWiki Error

Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Erfurt/Erfurt/Store/Adapter/Virtuoso.php, line 160
/apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Controller/Response/Abstract.php@323
Stacktrace:
#0 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /apps/udfr/apps/apache/htdocs/ontowiki/extensions/pingback/PingbackPlugin.php(40): Zend_Controller_Response_Abstract->setHeader('X-Pingback', 'http://udfr-tmp...', true)
#2 [internal function]: PingbackPlugin->onAfterInitController(Object(Erfurt_Event))
#3 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Erfurt/Erfurt/Event/Dispatcher.php(179): ReflectionMethod->invoke(Object(PingbackPlugin), Object(Erfurt_Event))
#4 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Erfurt/Erfurt/Event.php(178): Erfurt_Event_Dispatcher->trigger(Object(Erfurt_Event))
#5 /apps/udfr/apps/apache/htdocs/ontowiki/application/classes/OntoWiki/Controller/Base.php(165): Erfurt_Event->trigger()
#6 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Controller/Action.php(133): OntoWiki_Controller_Base->init()
#7 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Controller/Dispatcher/Standard.php(268): Zend_Controller_Action->__construct(Object(OntoWiki_Request), Object(Zend_Controller_Response_Http), Array)
#8 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(OntoWiki_Request), Object(Zend_Controller_Response_Http))
#9 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /apps/udfr/apps/apache/htdocs/ontowiki/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /apps/udfr/apps/apache/htdocs/ontowiki/index.php(157): Zend_Application->run()
#12 {main} (0)

**Comment by white-gecko** [comment]
Hello,
first the `… Cannot send headers; headers already sent …` error is not the actual problem. It is a follow-up issue because the other exception sends already output.

Are you using the current master oder develop branch? If you are using the master branch could you please try updating OntoWiki and Erfurt library to the current develop branch?

**Comment by cckweiss** [comment]
I am using the distribution under your 'Download' link on http://aksw.org/Projects/OntoWiki.html, from here:

https://github.com/downloads/AKSW/OntoWiki/ontowiki-0.9.6-21.7z

It is not clear to me how I obtain the OntoWiki and Erfurt library from the develop branch. Can you please provide links and an installation procedure?

--Ken

**Comment by cckweiss** [comment]
I did this:

git clone -b develop https://github.com/AKSW/OntoWiki

And got something...

udfr@uc3-udfr-prd:~/src/OntoWiki$ ls
application  build.xml        debian      index.php  Makefile   web.config
build        config.ini.dist  extensions  libraries  README.md

I have a few meetings now, but will try replacing my current OntoWiki installation with this later. Let me know if I didn't actually get the branch you wanted me to get.

--Ken

**Comment by white-gecko** [comment]
This should be the correct branch. Now you have to run "make deploy"

**Comment by cckweiss** [comment]
The development branch works, no problems at all. I just moved it into place, restarted Apache and Virtuoso, and it worked. Didn't change a line of configuration. All I need to do now is figure out how to clone my application and database from the old platform to the new one. Thanks for the help. 

As an aside, it's a bit counter-intuitive to have the working software in the development branch, and the broken software under the big 'Download' button on your home page... :-)

--Ken
