### ISSUE TITLE
ReferenceError: navigationAddElement is not defined

### ISSUE THREAD

**Issue by white-gecko** [AKSW/OntoWiki#319]
Calling the menu entry "Edit" > "Add Resource here" in the navigation module will result in the JavaScript error message

    ReferenceError: navigationAddElement is not defined

The menu entry actually calls "javascript:navigationAddElement()" which should be defined here: https://github.com/AKSW/OntoWiki/blob/develop/extensions/navigation/navigation.js#L384 but doesn't seam to work.

**Comment by white-gecko** [comment]
This bug was introduced with a233bf10ce939e96537267107ae0e2b2dcffc344

**Comment by white-gecko** [comment]
Hey @yamalight are you able to fix this issue?

**Comment by yamalight** [comment]
Sure, the question is when I'll have time for that. If you want it fixed fast, then I'd suggest looking into it yourself :)

**Comment by yamalight** [comment]
looks like it might be fixed by just adding `window.navigationAddElement = navigationAddElement;`

**Comment by white-gecko** [comment]
My guess is, that the function `navigationAddElement` is no longer available at the global level. So what actually is this `(function(){ … });` structure doing?

Where to add the `window.navigationAddElement = navigationAddElement;`?

**Comment by white-gecko** [comment]
Ah ok, I think I get it. I will try to fix it. Thank you!

**Comment by yamalight** [comment]
Cool :)
