### ISSUE TITLE
Troubles getting OntoWiki with XAMPP to run

### ISSUE THREAD

**Issue by pawlows-dog** [AKSW/OntoWiki#322]
Hello,

I have a great interest in OntoWiki and am trying to get it to run on windows 7 with XAMPP, including a mySQL database. I got as far as seeing the welcoming screen (with the same two hidden error messages that were reported here: https://groups.google.com/forum/#!topic/ontowiki-user/3VIvRVq5loo by another xampp user).
The moment I "create a new knowledge base" I got stuck in the same loop that was reported in link above. When I turn on debug mode in the config.ini I get the following report:

    Erfurt_Sparql_ParserException: Variable, iri or qname expected in FROM
    <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Erfurt\Erfurt\Sparql\Parser.php@944
    Stacktrace:
    #0 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Erfurt\Erfurt\Sparql\Parser.php(1427): Erfurt_Sparql_Parser->_parseFrom()
    #1 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Erfurt\Erfurt\Sparql\Parser.php(325): Erfurt_Sparql_Parser->_parseQuery()
    #2 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Erfurt\Erfurt\Store\Adapter\EfZendDb.php(1098): Erfurt_Sparql_Parser->parse('SELECT DISTINCT...')
    #3 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Erfurt\Erfurt\Store.php(1340): Erfurt_Store_Adapter_EfZendDb->sparqlQuery('SELECT DISTINCT...', Array)
    #4 <PathToInstallation>\XAMPP\htdocs\ontowiki\application\classes\OntoWiki\Model\TitleHelper.php(404): Erfurt_Store->sparqlQuery(Object(Erfurt_Sparql_SimpleQuery), Array)
    #5 <PathToInstallation>\XAMPP\htdocs\ontowiki\application\classes\OntoWiki\Model\TitleHelper.php(499): OntoWiki_Model_TitleHelper->getTitleQueryResult()
    #6 <PathToInstallation>\XAMPP\htdocs\ontowiki\application\classes\OntoWiki\Model\TitleHelper.php(335): OntoWiki_Model_TitleHelper->_fetchResourceTitlesFromQueryResult('__resource')
    #7 <PathToInstallation>\XAMPP\htdocs\ontowiki\extensions\modellist\ModellistModule.php(97): OntoWiki_Model_TitleHelper->getTitle('Test KB 1', 'en')
    #8 <PathToInstallation>\XAMPP\htdocs\ontowiki\application\classes\OntoWiki\View.php(265): ModellistModule->getContents()
    #9 <PathToInstallation>\XAMPP\htdocs\ontowiki\application\classes\OntoWiki\View.php(150): OntoWiki_View->module('modellist', NULL, 'main.sidewindow...')
    #10 <PathToInstallation>\XAMPP\htdocs\ontowiki\application\classes\OntoWiki\Controller\Base.php(180): OntoWiki_View->modules('main.sidewindow...')
    #11 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Zend\Controller\Action.php(502): OntoWiki_Controller_Base->preDispatch()
    #12 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
    #13 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(OntoWiki_Request), Object(Zend_Controller_Response_Http))
    #14 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
    #15 <PathToInstallation>\XAMPP\htdocs\ontowiki\libraries\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
    #16 <PathToInstallation>\XAMPP\htdocs\ontowiki\index.php(157): Zend_Application->run()
    #17 {main} (-1)

I am not a programmer and understand only so much of the IT-slang around. I know I haven't been able to somehow apply the "Makefile". But I have the latest archive (OntoWiki v0.9.6-21) with all the zend stuff in ow/libraries.

Any help would be greatly appreciated. I would really love to give OntoWiki a try. I am pretty deep into the application side of semantics, but usable tools are scarce. Ontowiki looks great.

Cheers,

Jan

**Comment by shinobu** [comment]
everything worked fine for me after downloading all (not only zend) libraries and adding them in `./libraries/`
