### ISSUE TITLE
problem when we try to add properites label at onto wiki

### ISSUE THREAD

**Issue by jane1661245** [AKSW/OntoWiki#323]
when we hit add property button . we want to add new label other than suggest  "General applicable (9)"
seems we can not simply add it.
how can we solve this problem..plz help.

**Comment by splattater** [comment]
Hello Jane, have you tried to manually enter the URI in the input field? Once you have added a property, it should be suggested in the "In use elsewhere" section.

**Comment by white-gecko** [comment]
Did the solution suggested by @splattater work for you? If not, please just reopen this issue.
