### ISSUE TITLE
Use Ontowiki with another RDF/OWL database than Virtuoso?

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/OntoWiki#326]
Dear all,

Is it possible to choice another RDF/OWL database. I would like to use Blazegraph.
But Blazegraph haven't ODBC driver. Have you an idea?

Thanks in advance,

**Comment by splattater** [comment]
Hello @cfrancois7,

you can write your own Erfurt store adapter by implementing the adapter interface or try to use the sparql adapter [1]. In OntoWiki's config.ini the setting 'store.backend' needs to be changed to switch to the backend adapter of your choice.

[1] https://github.com/AKSW/Erfurt/tree/develop/library/Erfurt/Store/Adapter

**Comment by dandrocec** [comment]
Hi,

Is the procedure the same if I want to use Apache Jena triple store as backend? Do I need to develop custom adapter for it, or some simpler solution exists? If I need to develop an adapter, what do you think, how complex is that effort?

Thanks,
Darko

**Comment by white-gecko** [comment]
Yes, you would also need to develop an Adapter for Erfurt. The complexity depends on the possibility to access the desired back-end from a PHP application.
