### ISSUE TITLE
Troubles install OntoWiki with Mysql database

### ISSUE THREAD

**Issue by zldeng** [AKSW/OntoWiki#330]
I install Ontowiki in Mac and I chose Mysql database. I do it according to the guide:
If you want to use OntoWiki with MySQL, here we go ... we assume, you have a copy of OntoWiki at your webdirectory.
1. create a mysql user for ontowiki (e.g. called "ontowiki")
2. create a mysql database which is writable for the ontowiki user
3. copy the config.ini-dist to config.ini and change the database config: in most cases, you have to change only these values store.zenddb.dbname, store.zenddb.username, store.zenddb.password
4. go to the ontowiki root dir, run 'make deploy' - sets up Zend etc.
5. open your OntoWiki Installation in our browser. On first run, all tables are created automatically and hopefully, you will see a starting screen containing a news area and a login window

I change store.zenddb.dbname, store.zenddb.username, store.zenddb.password in config.ini
**store.backend = zenddb
;; ZendDB / MySQL backend specific options
;;
store.zenddb.dbname   = "ontowiki"
store.zenddb.username = "php"
store.zenddb.password = "php"
store.zenddb.dbtype   = mysql
store.zenddb.host     = localhost**

I create a database ontowiki and grant all privileges to 'php'@'localhost' identified by php.
But when I open ontowiki installation in my browser. I get error infomation:

_Could not connect to database with name: "ontowiki". host:localhost username: php password: php". Please check your credentials and whether the database exists and the server is running.
Erfurt_Exception

/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Store/Adapter/EfZendDb.php@103 
#0: Erfurt_Store_Adapter_EfZendDb->_connect@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Store/Adapter/EfZendDb.php:57
#1: Erfurt_Store_Adapter_EfZendDb->__construct@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Store.php:261
#2: Erfurt_Store->__construct@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/App.php:917
#3: Erfurt_App->getStore@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Ac/Default.php:709
#4: Erfurt_Ac_Default->_init@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Ac/Default.php:354
#5: Erfurt_Ac_Default->isActionAllowed@/Library/WebServer/Documents/ontowiki/extensions/exconf/ExconfHelper.php:20
#6: ExconfHelper->__construct@/Library/WebServer/Documents/ontowiki/application/classes/OntoWiki/Extension/Manager.php:459
#7: OntoWiki_Extension_Manager->_loadHelper@/Library/WebServer/Documents/ontowiki/application/classes/OntoWiki/Extension/Manager.php:426
#8: OntoWiki_Extension_Manager->onRouteShutdown
#9: ReflectionMethod->invoke@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Event/Dispatcher.php:184
#10: Erfurt_Event_Dispatcher->trigger@/Library/WebServer/Documents/ontowiki/libraries/Erfurt/library/Erfurt/Event.php:180
#11: Erfurt_Event->trigger@/Library/WebServer/Documents/ontowiki/application/classes/OntoWiki/Controller/Plugin/SetupHelper.php:127
#12: OntoWiki_Controller_Plugin_SetupHelper->routeShutdown@/Library/WebServer/Documents/ontowiki/libraries/Zend/Controller/Plugin/Broker.php:260
#13: Zend_Controller_Plugin_Broker->routeShutdown@/Library/WebServer/Documents/ontowiki/libraries/Zend/Controller/Front.php:923
#14: Zend_Controller_Front->dispatch@/Library/WebServer/Documents/ontowiki/libraries/Zend/Application/Bootstrap/Bootstrap.php:101
#15: Zend_Application_Bootstrap_Bootstrap->run@/Library/WebServer/Documents/ontowiki/libraries/Zend/Application.php:366
#16: Zend_Application->run@/Library/WebServer/Documents/ontowiki/index.php:188_

I check the credentials,It is ok.
**mysql> show grants for 'php'@'localhost';
+-----------------------------------------------------------+
| Grants for php@localhost                                  |
+-----------------------------------------------------------+
| GRANT USAGE ON _._ TO 'php'@'localhost'                   |
| GRANT ALL PRIVILEGES ON `ontowiki`.\* TO 'php'@'localhost' |
+-----------------------------------------------------------+
2 rows in set (0.00 sec)**

I connect the database just using  php connect and It's successful.

I'm a ontowiki and php newer.
Anyone can help me.Thank you verify much.

**Comment by shinobu** [comment]
Did you activated the debug mode (last line in config.ini) to look at further errors?

Do you have mysqli and pdo_mysql activated?

**Comment by nhussain920** [comment]
I tried to install OntoWiki-0.9.10 on windows 10. I configured everything such as mysql accordingly.
but it shows the blank page. I tested the database connectivy and it is fine.

**Comment by white-gecko** [comment]
Have you also tried OntoWiki 1.0 ? Please enable debugging output for your PHP process. This should give relevant feedback to debug your problem.

**Comment by nhussain920** [comment]
HI, i am getting following error to install OntoWiki-0.9.1:
```
Warning: Uncaught ErrorException: require_once(Zend/Application.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ontowiki\index.php:135 Stack trace: #0 C:\xampp\htdocs\ontowiki\index.php(135): errorHandler(2, 'require_once(Ze...', 'C:\\xampp\\htdocs...', 135, Array) #1 C:\xampp\htdocs\ontowiki\index.php(135): require_once() #2 {main} thrown in C:\xampp\htdocs\ontowiki\index.php on line 135

Fatal error: main(): Failed opening required 'Zend/Application.php' (include_path='C:\xampp\htdocs\ontowiki\libraries/;C:\xampp\php\PEAR;') in C:\xampp\htdocs\ontowiki\index.php on line 135
```

**Comment by nhussain920** [comment]
OntoWiki 1.0 also not working. I tried to install both verison on Ubunutu 18.4 LTS as well, unfortunately could not success. Please give me clear step-by-step instruction to install any previous ontowiki version with mysql in windows 10. The installation instruction for windows on ontowiki site is not clear. Currently, I am running wampp server in my machine. I need this to be install to demonstrate my developed knowledged system for my PhD thesis.

**Comment by white-gecko** [comment]
Did you execute composer install? What did it output? Is Zend installed in the `vendor` directory?
As non of the OntoWiki core team is using Windows we would be happy, if you can help us improving the documentation at this front.

**Comment by nhussain920** [comment]
Hi, Thanks for the reply. Now I have tried to install ontowiki version 1.0 on Windows 10 with wamp64 server. Apache, php, and zend are running fine from localhost.
My folder structure of ontowiki installation is C:\wamp64\www\OntoWiki and all files and folders in there. I installed Zend framework in OntoWiki folder which created a Vendor folder. The folder structure for zend installation is C:\wamp64\www\OntoWiki\vendor\zendframework. Now having following error

"Fatal error: Uncaught Error: Class 'Zend_Application' not found in C:\wamp64\www\OntoWiki\index.php on line 122. In index file the line number 122-125 is
$application = new Zend_Application(
    'default',
    ONTOWIKI_ROOT . 'application/config/application.ini'
); 
If I need to change any path to fix it how to do this. Please help

**Comment by white-gecko** [comment]
You need to install zend using the composer because this will also configure the autoloader which is required to find the class `Zend_Application`.
