### ISSUE TITLE
Can't use "[" and "]" with Mac keyboard in the RDF editor

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/OntoWiki#332]
Dear all,

With a Mac Keyboard "[" and "]" could be displayed with `Alt+Maj+(` and `Alt+Maj+)` but that doesn't work with rdf editor on ontowiki e.g. when I want to edit a instance label.

I don't know how to resolve this problem. Have you an idea. For the moment I have to copy "[" I wrote in my research bar in my browser and paste it in the editor.

**Comment by cfrancois7** [comment]
EDIT: "[" and "]" work when I `add instance` or `add resource`, e.g. new Class, but don't work when I `add property`.

**Comment by pfrischmuth** [comment]
Which keyboard layout do you use? On my mac in order to get a `[` char I only have to press `alt + 5`. What is the `Maj` key?

**Comment by pfrischmuth** [comment]
@cfrancois7 Please re-open, if this still happens.

**Comment by cfrancois7** [comment]
I tried with the last version of ontowiki and the Amsl version. It still doesn't work.
My keyboard are a french version of a Mac keyboard. In fact, when I use the 'MAJ+something', nothing happen.

**Comment by cfrancois7** [comment]
Also, I can't re-open my own issues if a repo collaborator closed it.

**Comment by pfrischmuth** [comment]
Thank you for your response. I re-opened the issue and assigned it back to the 1.0 milestone. Can you just give me an hint what the "MAJ" key is on your keyboard? Thanks!

**Comment by cfrancois7** [comment]
Sorry. It's the Shift button in english.

**Comment by pfrischmuth** [comment]
Fixed in c7dc7f7. This fix will be part of the OntoWiki 1.0 release.
