### ISSUE TITLE
Property edition works with 'Edit Resource' but not with 'Edit properties' for instance in namespace 

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/OntoWiki#333]
Dear all,

I'm face with several issues regarding the edition of resources on ontowiki.
I'm using the AKSW templates

0. I use the "Admin" account
1. I uploaded a RDF with all relations into the namespace.
2. I **can't edit the resource properties** through the property edition menu and with "Edit Properties" **if this property is inside the namespace**.[Image](https://www.dropbox.com/s/9rea791hgn3nsz4/edition_resources_not_possible.png?dl=0)
3. But I can edit the resource properties through the `right click` on the resource instance and `edit resources`.[ Image](https://www.dropbox.com/s/r75kzxstkch8vu8/edition_resources.png?dl=0)
That's the first problem

The second problem is when I add property
0. I use the "Admin" account
1. same as above
2. The add of new property with the `Add property` works. I can create it but after I **can't edit **as seen above only **if this property is inside the namespace**.
3. If **I add new property** through the `Edit Resource` with `right click` on the resource instance **ontowiki freezes** **if the new property I add first isn't one of my property**.
[Image](https://www.dropbox.com/s/o0zdhiq6ix4q8ug/freeze.png?dl=0)

If now I upload the same RDF inside another database (with another namespace), the first problem is resolved. But not the second

I have nothing interesting in the ontowiki.log, erfuts.log, queries.log and cache.log.

**Comment by white-gecko** [comment]
Moved to https://github.com/AKSW/RDFauthor/issues/47

**Comment by white-gecko** [comment]
Maybe this is fixed on the AMSL branch already: https://github.com/amsl-project/RDFauthor/tree/7d7424478b160bafbfe71cb305a0ab7fbfe5e14c
