### ISSUE TITLE
CodeSniffer outdated

### ISSUE THREAD

**Issue by white-gecko** [AKSW/OntoWiki#334]
There are some remaining problems with our custom code sniffer rules. e.g. the doccomment. maybe `Squiz.Commenting.FunctionDocSniff` helps.

**Comment by white-gecko** [comment]
I've now also found this sniff, maybe it does, what we want: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php

**Comment by shinobu** [comment]
#352 fixes the remaining FileCommentSniff issues

**Comment by white-gecko** [comment]
We now also have to find a way to deal with files, created before 2009

**Comment by shinobu** [comment]
Getting the general creation time in linux seems to be not generally doable. It's depending on the used filesystem. But ext4 for example does save the birthtime of a file. But i would need to test later, if the files loses the timestamp after for example getting uploaded to git.

http://unix.stackexchange.com/questions/50177/birth-is-empty-on-ext4/50184#50184

**Comment by white-gecko** [comment]
Filesystem Dates will not help. I've solved this part of the question already in bf495062410fb7b2b0490a0fa3e0eef457ac797b, (but I will care about the rest, since this is assigned to me now ;-) )

**Comment by white-gecko** [comment]
Fixed in b82467df24591046bceef0cd1bfccb7796eecbf3, bf495062410fb7b2b0490a0fa3e0eef457ac797b, cc80d93b7492322c2c5208e4becc04a81783b1df, e80a01f84a96688e03c5a8e3c600a35161aed1bc, 24a161c6e72892e458e480a317211765c70c20ec, 0ec9f638d115152d040043bbc2ec600bd5a469e0, 6c3c723a73db64425ff1a51020611e98dcb56e42, 4d947185a0ebcaa8519e8a176c18902f664f8462, 5a242f1e61ea94241b275e4356a6defbf1d29ac1 and b35e2cb8a078d809976b2191d6bc18791ec7d9c9

**Comment by white-gecko** [comment]
One day we should get to http://www.php-fig.org/psr/psr-2/
