### ISSUE TITLE
Composer installation in Makefile is not optimal

### ISSUE THREAD

**Issue by white-gecko** [AKSW/OntoWiki#338]
We should find a better way of installing composer in the Makefile. The key has changed already: https://composer.github.io/pubkeys.html

**Comment by white-gecko** [comment]
Maybe we should also add a check, if a global composer is available in the path and else install it locally already in the deploy target.

**Comment by shinobu** [comment]
1. check if composer.phar exists in root
2. check if composer exists global (´which composer´)
3. if neither was successful download new version (wget)
4. save composer target path
