### ISSUE TITLE
Error in nagivation.js on amsl branch

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/OntoWiki#345]
Dear all,

I found a problem with the amsl ontowiki fork, but I don't know how and who to contact regarding the **amsl branch** problem. There is no issue menu on the github.
When I use the amsl version, there is a problem with the `add resource here` from the **navigation menu**. Indeed, in the `nagivation.js` file in the amsl branch there are two lines which are missing. See follow the code which is missing.

_navigation.js_
code which is missing at the end of the file.
The code comes from Ontowiki dev branch (which works), line 431-433:
```
// expose
    window.navigationAddElement = navigationAddElement;
})();
```
Without this code in the **amsl branch** the function `navigationAddElement()` doesn't work.

**Comment by white-gecko** [comment]
@cfrancois7 thank you for reporting, the issue, I think it is fine to report it here, since we want to try to get the amsl branch in sync again eventually.
@ReikMuellerUBL maybe you can try to integrate this fix?

**Comment by ReikMuellerUBL** [comment]
@cfrancois7 thank you for reporting! I inserted the line. Please have a look and feel free to contact us whenever you find further issues.

**Comment by white-gecko** [comment]
So, I guess, the issue can be closed.
