### ISSUE TITLE
FileCommentSniff fails for merge commits

### ISSUE THREAD

**Issue by white-gecko** [AKSW/OntoWiki#354]
The `FileCommentSniff` can't handle years in merge commits, since the date is in the 4th instead of 3rd line, see:
https://github.com/AKSW/OntoWiki/blob/develop/application/tests/CodeSniffer/Standards/Ontowiki/Sniffs/Commenting/FileCommentSniff.php#L94

**Comment by shinobu** [comment]
a quick fix for this would be to look for the year in line 4 if regex fails to find anything in line 3
