### ISSUE TITLE
The erfurt default.ini entry ac.deactivateRegistration doesn't get read propperly

### ISSUE THREAD

**Issue by shinobu** [AKSW/OntoWiki#390]
deactivating the registration in the (Erfurt) default.ini doesn't work.

**Comment by shinobu** [comment]
for some reason the entry needs to be in the OntoWiki .ini's to be found --- even then it just removes the entry in the top row in `User` not in the log in field (that register button still works)

update:

so in applications/classes/OntoWiki/Menu/Registry.php

`$owApp->config->ac->deactivateRegistration` is checked

and in extensions/account/LoginModule.php

`$this->_erfurt->getAc()->isActionAllowed('RegisterNewUser')` this

furthermore deactivating this doesn't invalidates the `**base_url**/application/register` url so in fact you can still register that way

**Comment by white-gecko** [comment]
For disabling the register action you should check the permissions within the action and output an error instead of the registration form if not allowed.

**Comment by shinobu** [comment]
done in #403
