### ISSUE TITLE
Admin has no property password

### ISSUE THREAD

**Issue by harshnisar** [AKSW/OntoWiki#393]
I just installed OntoWiki and I am following https://github.com/AKSW/OntoWiki/wiki/Getting-Started-Users.

I logged in as SuperAdmin and am trying to add the password field for Admin class:user.

When I clicked Add Property - password is not suggested in the list - and when I write password in the field it says invalid URI.

**Comment by harshnisar** [comment]
Screenshot of available options.

![ontowiki-user](https://cloud.githubusercontent.com/assets

**Comment by white-gecko** [comment]
If you are logged in as Administrator, you can change the password through the "User" menu.

**Comment by white-gecko** [comment]
@shinobu we should make sure, that this is documented.

**Comment by shinobu** [comment]
I added the information, that you can log in as Admin with an empty PW [here](http://docs.ontowiki.net/Getting-Started-Users.html#first-login) a while ago.

IIRC if you set the Password of the Admin as dba it doesn't use a SHA for saving it (though i'm not sure how I did add the PW back then). Shall I test it and add a more detailed way for adding it as dba or should I just delete the Option to add the PW for Admin as dba?
