### ISSUE TITLE
Erfurt log.path not writable (CentOS 7)

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/OntoWiki#422]
I'm currently installing an ontowiki on a CentOS 7 with nginx.
Everything seemed to be good before I got "Internal Server Error" when I try to connect to my localhost.
However, I tried to activate the debug mode of ontowiki to get the trace of the error. The only log that seems to be relevant is:
`$ cat /var/log/php-fpm/www-error.log`
`Erfurt log.path (/usr/share/nginx/html/ontowiki/logs/) not writable`

but the dir logs is 777 and I tried every user (apache, nginx). The problem is I have no other error log except this one and I don't understand where the problem is (php-fpm ? or virtuoso-ontowiki ?).

**Comment by white-gecko** [comment]
if the directory `/usr/share/nginx/html/ontowiki/logs/` is 777 is there already any file in the directory with different access rights?

**Comment by cfrancois7** [comment]
I decided to switch from my server to my MacOs laptop but now I experienced problem with nginx which is anormally slow to display page I explained in the newer topic I posted.

I'll try in few months to build ontowiki on the server side. I propose you to close the topic for the moment.
