### ISSUE TITLE
Erfut error: Virtuoso adapter requires the ODBC extension to be loaded.

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/OntoWiki#424]
EDIT:

When I try to access the page on my localhost (localhost/~myName/ontowiki) I got this message in the ontowiki.log:
Erfurt_Store_Adapter_Exception: Virtuoso adapter requires the ODBC extension to be loaded. -> `/Users/myName/Sites/ontowiki/vendor/aksw/erfurt/library/Erfurt/Store/Adapter/Virtuoso.php@104`

I can properly connect my virtuoso with Isql and I tested the OCDB driver, everything works fine. I just don't know how to run the ODBC extension here.

**Comment by cfrancois7** [comment]
I restarted my computer and now I got the next error:

Virtuoso adapter requires the ODBC extension to be loaded.
It is the same error than [here](https://github.com/p6data-coop/ise-linked-open-data/wiki/OntoWiki-Installation-Mac-OS). But there is no solution provided.

**Comment by cfrancois7** [comment]
The problem seems to not come from php because `odbc_connect('VOS', 'dba', 'dba')` works fine.

```
$ make odbctest
Your connection to Virtuoso seems to work fine
```

**Comment by white-gecko** [comment]
Is this on MacOSX?

**Comment by pfrischmuth** [comment]
Can you please check the `phpinfo()` output page within your web browser? Is the ODBC extension loaded there? Maybe your CLI PHP uses another configuration file?

**Comment by cfrancois7** [comment]
Yes it is on mac, and yes indeed the odbc extension was not installed with the build-in php5.5 (and It seems to be too complicated to add the extension).
I decided to install from sources through homebrew and now the extension is loaded. 

But again, I have to deal with the same problem than Nginx. The time to load a page is very very long. See [here the problem with Nginx](https://github.com/AKSW/OntoWiki/issues/423).

It is normal that the first page of my database (on virtuoso 20 Go) takes a dozen of minutes to load ?
Once again, I don't find a log file with any interesting information : log/ontowiki.log => nothing, erfurt.log => nothing, apache2/error.log => nothing, virtuoso.log => nothing interesting too.

**Comment by cfrancois7** [comment]
You can close this topic. With the packages from homebrew (http24 and php --with-unixodbc) everything is good with ODBC. If there is problem to define the configuration, just use the iODBC administrator tools from OpenLinks.
