### ISSUE TITLE
Several odd behaviors on a new installation

### ISSUE THREAD

**Issue by scossu** [AKSW/OntoWiki#433]
I am very new to Ontowiki, actually evaluating it. 

I installed the app on Debian Squeeze with a Virtuoso backend. I compiled the latest Virtuoso (7.2.4.2) from source. 

I created a new empty KB and added all the vocabularies available in the stock distribution: SKOS, FOAF, SIOC, etc. 

I see my KB on the left hand side navigation menu (called "SKOS Vocabulary").

First off, if I click on the KB link on the left hand menu it sends me to the home page with the news. No class menu is shown below the KB menu. 

I know that the class menu should be showing up because It had work in a different setup, but I cannot replicate the correct behavior any more. 

Also, if  I click on any of the "graph" icons that appear on the KB menu items, I get a pop-up with a spinning wheel that doesn't load anything else. 

In my browser console I see that the AJAX request result in an error:

```SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data```

and this is the response from the server: 

```
<br />
<b>Notice</b>:  Undefined variable: menu in <b>/var/www/ontowiki/application/controllers/ServiceController
.php</b> on line <b>146</b><br />
<br />
<b>Notice</b>:  Undefined variable: menu in <b>/var/www/ontowiki/application/controllers/ServiceController
.php</b> on line <b>156</b><br />
<br />
<b>Fatal error</b>:  Call to a member function toJson() on null in <b>/var/www/ontowiki/application/controllers
/ServiceController.php</b> on line <b>156</b><br />
```

In this case too I had it working in a different setup and I can no longer replicate it. 

For what is worth, the same also happens  with a MySQL backend. 

Any help is appreciated. Thank you.

**Comment by white-gecko** [comment]
Thank you for reporting this issue. I could find the according place in the code. But anyways. Which version of OntoWiki are you using?

**Comment by white-gecko** [comment]
Could you also provide me with the URLs of the AJAX request, as well as you base URL of the OntoWiki installation?

**Comment by white-gecko** [comment]
If you use this branch https://github.com/AKSW/OntoWiki/tree/feature/menuProduceError you shouldn't get the AJAX errors anymore, but a message in the menu

**Comment by white-gecko** [comment]
Did you manage to fix this error?

**Comment by scossu** [comment]
Sorry for the late notice, I only received your last message in my email. 

I have not fixed this in my own setup. Installing from Docker worked well but I have since deleted the self-built one. It should have been the current Github branch at that time. If I get a chance to rebuild it I will try the branch you are suggesting.
