### ISSUE TITLE
Widgets are not displayed

### ISSUE THREAD

**Issue by MaherBTA** [AKSW/OntoWiki#436]
![home_page](https://user-images.githubusercontent.com/16023366/36872241-e2f5d88e-1da4-11e8-89b3-939853b7ba31.png)
Hi, 
I managed to install ontowiki, but in the home page I don't find most of the widgets. I only find the logging widget.
No errors in the logs folder.

**Comment by white-gecko** [comment]
The default login should be username: Admin and empty password. Das that work?

**Comment by MaherBTA** [comment]
Thanks this worked for me.
is this what supposed to be like ??

![t](https://user-images.githubusercontent.com/16023366/36911851-28d3af70-1e45-11e8-9e72-f52064cf9c15.png)

**Comment by white-gecko** [comment]
Yes, that looks good.
